name: Update Pull request notes from commit messages

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  unit-tests:
    name: Code style & unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U logchange
      - name: Get Pull Request commit messages
        id: commits
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const result = [];
            const response = await octokit.request('GET /repos/{owner}/{repo}/pulls/{pull_number}/commits', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ context.payload.number }}
            });
            response.forEach(commit => result.push(commit.commit.message));
            console.log(result);
            return result.join("\n");
      - name: Get new Pull Request body
        id: body
        env:
          BODY: ${{ context.payload.pull_request.body }}
          COMMITS: ${{ steps.commits.outputs.result }}
        run: |
          RESULT=`python -m logchange format -i "${BODY}\n${COMMITS}"``
          echo ${RESULT}
          echo "::set-output name=result::${RESULT}"
      - name: Update Pull Request
        id: commits
        uses: actions/github-script@v3
        env:
          BODY: ${{ steps.body.outputs.result }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const result = [];
            const response = await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ context.pull_request.number }}
              body: process.env.BODY,
            });
